### ISSUE TITLE
Syncing Todo and Calendar

### ISSUE THREAD

**Issue by stephaniedeleon** [CourseHeroGrp1/Planner#19]
- [x] sync task due dates with calendar while adding
- [x] sync task due dates with calendar when updating
- [x] delete event associated with deleted task
- [x] sync due dates in tasks when updating in calendar
- [x] delete task associated with deleted event
- [x] syncing edit event/task with updated event & task
