### ISSUE TITLE
Todo and calendar improvement

### ISSUE THREAD

**Issue by stephaniedeleon** [CourseHeroGrp1/Planner#20]
- [x] add tags for subtabs
- [x] add notes for calendar
- [x] show tags for tasks
- [x] change delete confirmation for deleting both task and event
- [x] add view more details for components
- [x] separate completed and not completed tasks
- [x] separate completed and not completed automatically
